sudo: false
language: node_js
node_js:
  - '7'
  - '8'
repo_token: C94YoWcSrQ9K6vJER1RBzPOYyE9N2I2LR
matrix:
  include:
    - node_js: "8.0"
      env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
  allow_failures:
    # Allow the nightly installs to fail
    - env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
sudo: false
cache:
  directories:
    - node_modules
install:
  - npm i npminstall && npminstall
script:
  - npm run test-ci
after_script:
  - npm install codecov && codecov